@api = http://localhost:4000/api/auth

### post register
POST {{api}}/register
Content-Type: application/json

{
  "username": "ryan2",
  "email": "ryan2@gmail.com",
  "password": "ryanpsasword"
}

### post login
POST {{api}}/login
Content-Type: application/json

{
  "email": "ryan2@gmail.com",
  "password": "ryanpsasword"
}

### verified token
GET {{api}}/verify

### Logout
POST {{api}}/logout